---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "microsam"
description: Segment Anything for Microscopy. Automatic segmentation of microscopy data
keywords:
  - segmentation
  - microscopy
  - image analysis
tools:
  - "microsam":
      ## TODO nf-core: Add a description and other details for the software below
      description: "Segment Anything for Microscopy. Automatic segmentation of microscopy data"
      homepage: "https://computational-cell-analytics.github.io/micro-sam/micro_sam.html"
      documentation: "https://computational-cell-analytics.github.io/micro-sam/micro_sam.html"
      tool_dev_url: "https://github.com/computational-cell-analytics/micro-sam"
      doi: "https://doi.org/10.1101/2023.08.21.554208 "
      licence: "MIT License"
      identifier: microsam_1_1_1

## TODO nf-core: Add a description of all of the variables used as input
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1']`
  
    - image:
        type: file
        description: Can either be a single image file (e.g. tif or png), or a container file (e.g. hdf5 or zarr)
        pattern: "*.{tif,tiff,png,h5,zarr}"
        
          

## TODO nf-core: Add a description of all of the variables used as output
output:
  - mask:

    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1']`
    - "*mask.tif":
        type: file
        description: Tif file with the segmentation masks for the input images
        pattern: "*.{tif}"
                 
  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@CaroAMN"
maintainers:
  - "@CaroAMN"
